### ISSUE TITLE
Rails version

### ISSUE THREAD

**Issue by rctneil** [everydayrails/rspec_rails_4#1]
Should this be Rails 4 in the updated version?

"In Everyday Rails Testing with RSpec I’ll walk you through taking a basic Rails 3.2"

**Comment by ruralocity** [comment]
Thanks, I've fixed that and will push it up to Leanpub once I've got a few other things taken care of.

**Comment by ruralocity** [comment]
I'm generating an update which addresses this (among a few other things) right now; should be available for download from Leanpub in the next 10 minutes or so.
