### ISSUE TITLE
RSpec version

### ISSUE THREAD

**Issue by belucid** [everydayrails/rspec_rails_4#10]
In the Introduction is this bullet:

• RSpec 2.14: I began writing this book while version 2.8 was current, so anything you see here should apply to versions of RSpec at least that far back.

Since 2.8 is > 2.14, I assume this is meant to say 1.8?

**Comment by ruralocity** [comment]
2.8 is correct. See the gem version history for more: http://rubygems.org/gems/rspec/versions

**Comment by belucid** [comment]
Oh my. 2.14 not 2.1.4. My bad!
