### ISSUE TITLE
Ch.3 - `expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)` is not a good example

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#100]
I think this example is not a good one.

``` ruby
  it "is invalid without a firstname" do
    expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)
  end
```

This is because the following examples also pass.

``` ruby
  it "is invalid without a firstname" do
    expect(Contact.new(email: nil)).to have(1).errors_on(:firstname)
  end
```

``` ruby
  it "is invalid without a firstname" do
    expect(Contact.new(firstname: nil)).to have(1).errors_on(:email)
  end
```

In my opinion, it should be like this:

``` ruby
  it "is invalid without a firstname" do
    contact = Contact.new(
      firstname: nil,
      lastname: 'Sumner',
      email: 'tester@example.com')
    expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)
  end
```

**Comment by ruralocity** [comment]
Since `have` has been extracted from the core, and `errors_on` has been removed from rspec-rails, I have rewritten these examples for the RSpec 3 version.

**Comment by jmcervera** [comment]
Please I really appreciate if you could give a sample of the replacement.
I am struggling to find a solution.
I am a reader of your book, and the solution given in the chapter 12 seems not to work with the final release.
I mean something like this doesn't work
expect(Contact.new(firstnmame: nil).errors_on(:firstname).size).to eq(1)
