### ISSUE TITLE
Code snippets not visible in kindle version of the book

### ISSUE THREAD

**Issue by mkreyman** [everydayrails/rspec_rails_4#101]
I bought and downloaded the book on March, 9. Unfortunately, I wasn't able to read it on my kindle, as commands to execute aren't visible in the kindle version. PDF version reads ok though.

**Comment by ruralocity** [comment]
Hi Mark, I'm forwarding this to Leanpub support. They take care of rendering the book in its different formats, and I don't own a Kindle myself to check it. 

Aaron

**Comment by ruralocity** [comment]
@mkreyman did this get resolved?

**Comment by mkreyman** [comment]
Yes, the code is visible now, even in the Kindle version of the book. Thank you!

**Comment by ruralocity** [comment]
Great, I'm going to close the issue.
