### ISSUE TITLE
第8页

### ISSUE THREAD

**Issue by breakliu** [everydayrails/rspec_rails_4#11]
我又新写了一章,通过为演示程序添加新功能,延时了 TDD 流程

应该是

我又新写了一章,通过为演示程序添加新功能,`演示`了 TDD 流程

**Comment by breakliu** [comment]
sorry, I think this is the rspec_rails_4_cn version. :)

**Comment by ruralocity** [comment]
OK, can I close this or should I ask @AndorChen to have a look?

**Comment by breakliu** [comment]
Yes, thank you.

**Comment by AndorChen** [comment]
@ruralocity @imlcl I got it. Will fix in next publish.

**Comment by breakliu** [comment]
Thx
:+1:
