### ISSUE TITLE
Ch.02 - set_up can't run  rspec 

### ISSUE THREAD

**Issue by mydearxym** [everydayrails/rspec_rails_4#111]
thanks for the work 

the issue is when i run rspec in chapter 2 (setup) i get the follow error 
i do the exactly as the book says 
please help ~

the error is :
➜ spec git:(02_setuporigin/02_setup) ✗ rspec
/Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:896:in `load': cannot load such file -- /Users/xieyiming/code/rspec_rails_4/spec/spec (LoadError)
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:896:in`block in load_spec_files'
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:896:in `each'
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/configuration.rb:896:in`load_spec_files'
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:80:in`run'
    from /Users/xieyiming/.rvm/gems/ruby-1.9.3-p484@rspect_test/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:17:in `block in autorun'

**Comment by ruralocity** [comment]
This may be too simple of an answer, but I'm wondering if you're running rspec inside your application's directory, or the `spec` directory. I don't think running it in `spec` would work.

**Comment by ruralocity** [comment]
Haven't heard anything, so I'm closing this issue. Please re-open if you're running specs from the correct directory (application root) and still seeing these errors.
