### ISSUE TITLE
CH3: Testing validations: errors_on checks report opposite results from book

### ISSUE THREAD

**Issue by zebrastealer** [everydayrails/rspec_rails_4#117]
Getting puzzling results - code in 'contact_spec.rb' file is identical to that in Chapter 3, however results received have been the opposite expected.   I finally used the 'contact_spec.rb' file from this repository (Chapter 3 branch) and the results are the same - the errors_on checks aren't returning correctly:

require 'spec_helper'

describe Contact do
  it "is valid with a firstname, lastname and email" do
    contact = Contact.new(
      firstname: 'Aaron',
      lastname: 'Sumner',
      email: 'tester@example.com')
    expect(contact).to be_valid
  end

  it "is invalid without a firstname" do
    expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)
  end

  it "is invalid without a lastname" do
    expect(Contact.new(lastname: nil)).to have(1).errors_on(:lastname)
  end

  it "is invalid without an email address" do
    expect(Contact.new(email: nil)).to have(1).errors_on(:email)
  end

  it "is invalid with a duplicate email address" do
    Contact.create(
      firstname: 'Joe', lastname: 'Tester',
        email: 'tester@example.com')
    contact = Contact.new(
      firstname: 'Jane', lastname: 'Tester',
        email: 'tester@example.com')
    expect(contact).to have(1).errors_on(:email)
  end

  it "returns a contact's full name as a string" do
    contact = Contact.new(firstname: 'John', lastname: 'Doe',
      email: 'johndoe@example.com')
    expect(contact.name).to eq 'John Doe'
  end

  describe "filter last name by letter" do
    before :each do
      @smith = Contact.create(firstname: 'John', lastname: 'Smith',
        email: 'jsmith@example.com')
      @jones = Contact.create(firstname: 'Tim', lastname: 'Jones',
        email: 'tjones@example.com')
      @johnson = Contact.create(firstname: 'John', lastname: 'Johnson',
        email: 'jjohnson@example.com')
    end

```
context "matching letters" do
  it "returns a sorted array of results that match" do
    expect(Contact.by_letter("J")).to eq [@johnson, @jones]
  end
end

context "non-matching letters" do
  it "returns a sorted array of results that match" do
    expect(Contact.by_letter("J")).to_not include @smith
  end
end
```

  end
end

However, running 'bundle exec rspec' yields failures on those checks for invalid for lastname/firstname: nil and email address duplicate):

C:\Users\Admin\how_i_test>bundle exec rspec
DL is deprecated, please use Fiddle

Contact
  is invalid with a duplicate email address (FAILED - 1)
  is valid with a firstname, lastname and email
  is invalid without a lastname (FAILED - 2)
  is invalid without an email address (FAILED - 3)
  returns a contact's full name as a string (FAILED - 4)
  is invalid without a firstname (FAILED - 5)
  filter last name by letter
    matching letters
      returns a sorted array of results that match (FAILED - 6)
    non-matching letters
      returns a sorted array of results that match (FAILED - 7)

Failures:

  1) Contact is invalid with a duplicate email address
     Failure/Error: expect(contact).to have(1).errors_on(:email)
       expected 1 errors on :email, got 0
     # ./spec/models/contact_spec.rb:31:in `block (2 levels) in <top (required)>'

  2) Contact is invalid without a lastname
     Failure/Error: expect(Contact.new(lastname: nil)).to have(1).errors_on(:lastname)
       expected 1 errors on :lastname, got 0
     # ./spec/models/contact_spec.rb:17:in `block (2 levels) in <top (required)>'

  3) Contact is invalid without an email address
     Failure/Error: expect(Contact.new(email: nil)).to have(1).errors_on(:email)
       expected 1 errors on :email, got 0
     # ./spec/models/contact_spec.rb:21:in `block (2 levels) in <top (required)>'

  4) Contact returns a contact's full name as a string
     Failure/Error: expect(contact.name).to eq 'John Doe'
     NoMethodError:
       undefined method `name' for #<Contact:0x0000000540c8b0>
     # ./spec/models/contact_spec.rb:37:in`block (2 levels) in <top (required)>'

  5) Contact is invalid without a firstname
     Failure/Error: expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)
       expected 1 errors on :firstname, got 0
     # ./spec/models/contact_spec.rb:13:in `block (2 levels) in <top (required)>'

  6) Contact filter last name by letter matching letters returns a sorted array of results that match
     Failure/Error: expect(Contact.by_letter("J")).to eq [@johnson, @jones]
     NoMethodError:
       undefined method `by_letter' for #<Class:0x0000000562c4b0>
     # ./spec/models/contact_spec.rb:52:in`block (4 levels) in <top (required)>'

  7) Contact filter last name by letter non-matching letters returns a sorted array of results that match
     Failure/Error: expect(Contact.by_letter("J")).to_not include @smith
     NoMethodError:
       undefined method `by_letter' for #<Class:0x0000000562c4b0>
     # ./spec/models/contact_spec.rb:58:in`block (4 levels) in <top (required)>'

Finished in 0.105 seconds
8 examples, 7 failures

Failed examples:

rspec ./spec/models/contact_spec.rb:24 # Contact is invalid with a duplicate email address
rspec ./spec/models/contact_spec.rb:16 # Contact is invalid without a lastname
rspec ./spec/models/contact_spec.rb:20 # Contact is invalid without an email address
rspec ./spec/models/contact_spec.rb:34 # Contact returns a contact's full name as a string
rspec ./spec/models/contact_spec.rb:12 # Contact is invalid without a firstname
rspec ./spec/models/contact_spec.rb:51 # Contact filter last name by letter matching letters returns a sorted array of results that match
rspec ./spec/models/contact_spec.rb:57 # Contact filter last name by letter non-matching letters returns a sorted array of results that match

Randomized with seed 15878

**Comment by smith** [comment]
I got at-mentioned in an instance variable :)

**Comment by zebrastealer** [comment]
Ok, have realized that I did not have anything in the app/model directory.  I think the book could use some reorganization in the front, I made an incorrect assumption that we'd be building everything from scratch going through the first few chapters and not have to figure out which files to cherry pick from the repository to get the tests to work. I'd suggest having a separate repository for each chapter that doesn't include any of the files from the current chapter that the 'studen't is going to modify, just the required files - i.e. the app/model files, possibly the database config files.  

Also, I think having a brief explanation about the app/model files would be useful in terms of understanding what we're about to validate against with our spec/model files, I was baffled for a few hours trying to figure out the 'magic' that was supposed to be happening to set the attributes (yes I'm a novice, but think a lot of readers of the book fit into this category). 

i.e:  contact.rb - before we dive into creating the contact_spec.rb file, the author should first mention that the app/model files must be copied into the appropriate directory, and possibly review the file...

class Contact < ActiveRecord::Base
  has_many :phones
  accepts_nested_attributes_for :phones

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true

  def name
    [firstname, lastname].join(' ')
  end

  def self.by_letter(letter)
    where("lastname LIKE ?", "#{letter}%").order(:lastname)
  end
end

**Comment by ruralocity** [comment]
I'm sorry you found the book's setup to be confusing. To clarify, my intent is not to teach the reader Rails, or even start off with test-driven development, but to work from a basic, functional application that does not yet have any tests. In other words, I expect the reader to have some basic knowledge of Rails and be ready to learn how to test the way that worked for me and others. Listing and explaining each file in the application would distract from the focus on testing.

Each chapter builds off the previous one, and the git repository is set up so that each chapter has its own branch showing the final code for it. So, for example, if you want to work on chapter 4, check out chapter 3 and follow along from there. I do not plan on making a repo for each chapter, as maintaining the sample source each time there's a significant update to Rails, RSpec, Capybara, etc. is cumbersome enough as it is.

If you're looking for a book that introduces Rails and RSpec simultaneously, I suggest Michael Hartl's Rails Tutorial.

Aaron

**Comment by ruralocity** [comment]
I'm closing this issue; feel free to reopen it if you've got further feedback on this matter. Thanks.
