### ISSUE TITLE
Ch. 2 page 8 - Typo

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [everydayrails/rspec_rails_4#118]
At the bottom of page 8 (PDF version), a word is missing:
"we’ll need to take a moment to install it and a few helpers"

Probably should be:
"we’ll need to take a moment to install it and _add_ a few helpers"

**Comment by ruralocity** [comment]
That's not really what I meant (we're not installing Rails helpers) but I've cleaned this up for the RSpec 3 edition to clarify.
