### ISSUE TITLE
bin/rspec not being created? (ref chap2, pg 18)

### ISSUE THREAD

**Issue by bjpcjp** [everydayrails/rspec_rails_4#119]
Here's the setup:
OS: Ubuntu 14.04 LTS
Ruby: 2.0.0-p353
Rails: 4.1.5
Rspec: 3.1.0

I followed the Ch2 setup instructions w/o issue, but $ bin/rspec returns "no such file or directory". Seems like a simple problem, but I'm stymied. Suggestions?

**Comment by ruralocity** [comment]
Try this:

bundle install --binstubs

If that works, let me know and I'll mention it in the book.

**Comment by bjpcjp** [comment]
Yep, $bundle install --binstubs did the trick. $bin/rspec now runs w/o
issue.

Props!
@brianpiercy
