### ISSUE TITLE
small error in chapter 3

### ISSUE THREAD

**Issue by rriksma** [everydayrails/rspec_rails_4#12]
Just a small issue, but there's this in chapter 3. Model specs

"We’ll expand this outline in a few minutes, but this gives us quite a bit for starters. It’s a simple spec for an admittedly simple model, but points to our first three best practices:"

Then you list four best practices.

If i happen to find anything else i'll let you know.
Thanks for the good work so far!

**Comment by ruralocity** [comment]
Wow, good find. That's probably been in there for about 18 months. I'm publishing an updated version now. Thanks!
