### ISSUE TITLE
Code mistake in Chapter 5 - line 49

### ISSUE THREAD

**Issue by lgoularte** [everydayrails/rspec_rails_4#14]
There is a mistake in the following code. Where you said "message", maybe you wanted to say "contact". 

it "redirects to the home page upon save" do
  post :create, message: FactoryGirl.attributes_for(:contact) expect(response).to redirect_to root_url
end

**Comment by ruralocity** [comment]
Hi, do you have the most recent version of the book? This was fixed it late August.
