### ISSUE TITLE
Code mistake in Chapter 5 - line 64

### ISSUE THREAD

**Issue by lgoularte** [everydayrails/rspec_rails_4#15]
In the following code, where you said "Message", maybe you wanted to say "Contact".

expect(Message.to_csv).to match /Aaron Sumner,aaron@sample.com/

In the chapter 5, there are other places where I guess you exchanged "contact" for "message", but these other mistakes do not compromise the understanding of the text.

This is a great book, thank you!

**Comment by ruralocity** [comment]
Thank you! Again, I think this was fixed already (an earlier edition of the book used a Message model for these examples), but if you're seeing it in the most recent release of the book let me know and I'll see why the old content is appearing.
