### ISSUE TITLE
Minor typo in Chapter 8: Feature specs

### ISSUE THREAD

**Issue by mayra-cabrera** [everydayrails/rspec_rails_4#16]
![screen shot 2013-10-20 at 3 37 27 pm](https://f.cloud.github.com/assets/4439027/1368895/30098ed4-39c7-11e3-88c9-f72e59dd5c91.png)

Filename extension should be shared_db_connection.rb instead of shared_db_connection.db. Great book!

**Comment by ruralocity** [comment]
Hi, thanks for the feedback and I'm glad you're enjoying the book! This was actually fixed in a previous update—do you have the latest version of the book?

**Comment by mayra-cabrera** [comment]
I supposed not, I have the version published on 2013-08-21. How can I get the latest version? Thanks!

**Comment by ruralocity** [comment]
Go to leanpub.com and sign in with the account you created when purchasing. If you have trouble accessing from there, email hello@leanpub.com and they can help!

**Comment by mayra-cabrera** [comment]
I got the update! Thanks :)
