### ISSUE TITLE
Chapter 7: Using custom RSpec matchers: `expect(attribute)` should be `expect(actual)`

### ISSUE THREAD

**Issue by johnpray** [everydayrails/rspec_rails_4#17]
In line 3 of the code in this section, `expect(attribute).to` should instead read `expect(actual).to`, since you're testing what actually happened instead of an expected attribute (which isn't even passed in in this example).

It becomes clearer if you look at RSpec Wiki's sample code that you link to at the end of the section: https://github.com/dchelimsky/rspec/wiki/Custom-Matchers They use `expected` instead of `attribute`, which makes the distinction a little clearer.

Thanks for a really great book!

**Comment by ruralocity** [comment]
Thanks for the feedback and sorry I missed this typo. I'm away from my computer for the rest of the week but will release an update when I'm back. Glad you're enjoying the book!

**Comment by ruralocity** [comment]
Fixed and preparing an update. Thanks again.
