### ISSUE TITLE
Difference between naming of spec examples in chapter 5

### ISSUE THREAD

**Issue by warlck** [everydayrails/rspec_rails_4#18]
In new version of book, chapter 5, the spec example names in page 49 and the names given with implementation in following pages are different...

**Comment by ruralocity** [comment]
Could you tell me what the publication date of your copy is? It's at the front of the book. This is a problem that was corrected back in July or August or so.

If you've got the current version of the book and still see a problem, could you tell me specific page numbers? Thanks.

**Comment by ruralocity** [comment]
@warlck I'm closing this issue; if you still see it in the current version (late October 2013 or newer) let me know and I'll reopen.
