### ISSUE TITLE
Alignment of method arguments throughout the book

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#19]
Some code examples use nicely aligned method arguments (e.g. page 20) while others have no alignment at all (e.g. page. 22, 24, 25). The aligned versions are much easier to read. 
Consider aligning all examples in the book to both be consistent and clear.

_Book version:  2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
I'll try to get this cleaned up in the next week.

**Comment by ruralocity** [comment]
I'll review this the next time I do a major update on the source. Closing for now.
