### ISSUE TITLE
Using the new syntax for mocks

### ISSUE THREAD

**Issue by kevinmcconnell** [everydayrails/rspec_rails_4#2]
As the book has been updated to use RSpec's newer `expect()` syntax, would it be worth updating the Mocks and Stubs section to use the [newer expectation syntax](http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/) too?

e.g.

``` ruby
Contact.stub(:persisted?).and_return(true)
```

could now be

``` ruby
allow(Contact).to receive(:persisted?).and_return(true)
```

Of course both are fine, but it seems like RSpec is moving in the direction of the latter.

**Comment by ruralocity** [comment]
Good point. I'll get this updated.

**Comment by ruralocity** [comment]
I've updated this in the 2013-08-21 release of the book. Thanks again.

**Comment by lentil** [comment]
Awesome.  Thank you!
