### ISSUE TITLE
P.9, Gemfile - Outdated gems

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#20]
The Gemfile contains the following outdated gems:
- faker 1.1.2 (newest is 1.2.0)
- database_cleaner 1.0.1 (newest is 1.2.0)
- selenium-webdriver 2.35.1 (newest is 2.37.0)

The lines just below the Gemfile state that:

> These are the current versions of each gem as of this writing.

which is not entirely true since the book was updated a few days ago, and some of these gems were updated much longer ago.

I've made it to chapter 4 with the newer versions without any problems so far.

_Book version:  2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
I'm going to change the wording of that sentence, because updating the entire app every time a supporting gem is updated is very time-consuming.
