### ISSUE TITLE
02_setup branch - Mismatch between text and code

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#21]
The Gemfile in the **02_setup** branch of the code uses version _2.33.0_ of `selenium-webdriver`, but the corresponding code in the book (page 9) uses version _2.35.1_.
Both versions are outdated (see my earlier issue report), but they should at least be consistent.

_Book version:  2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
The sample project is now set to 2.35.1 to match the book.
