### ISSUE TITLE
Ch3, p.29, code - Where did this spec come from?

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#24]
On page 29 in the code example `contact_spec.rb` the spec constructed through the chapter is shown in its full. But, where did the _"is invalid without email address"_ spec body come from? It's block is included in the skeleton created in the beginning of the chapter (page 17), but it isn't mentioned anywhere until here where the full body appears. All the other specs are mentioned and the reader is guided through writing them in the chapter. At least there should be a note about leaving this spec to the reader as an exercise if that's the intention.

_Book version:  2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
Noted for a future edition but not going to change the current version.
