### ISSUE TITLE
Ch3, p.31 - Words missing

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#25]
Page 31, section "How DRY is too DRY"?, third-last line:

> Even better, when we get into testing users with specific roles in chapter 6, might be variables like @admin_user and @guest_user.

There's a word or two missing in this sentence. Did you mean "..there might be variables like.."?

_Book version:  2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
No, that's not what I meant, but I have restructured the sentence to clarify for the next update.
