### ISSUE TITLE
Ch.4, p.38 - Spurious method usage

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#26]
In the `contact_spec.rb` code example on page 38 the `has a valid factory` test suddenly uses `create` instead of `build` compared to the not-so-lean test on page 36. I don't believe `create` is necessary here.

_Book version: 2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
Fixed to match what was already in the sample project source; to be included in the next update.
