### ISSUE TITLE
Ch.4, p.41/42 - Unnecessary require

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#29]
The `contacts.rb` and `phones.rb` examples on page 41 and 42 both have the `require 'faker'` statement. I accidentally left it out in my Phone factory, but it seems everything works fine without it. I have no idea why, but I have now also removed it from the Contact factory and everything seems to work fine - less is more, right :-)

_Book version: 2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
Probably a habit I carried over from earlier versions of Rails. I removed the unnecessary code for the RSpec 3 update.
