### ISSUE TITLE
Use ffaker instead of faker?

### ISSUE THREAD

**Issue by gmile** [everydayrails/rspec_rails_4#3]
[`ffaker`](https://github.com/EmmanuelOga/ffaker) author claims it is orders of magnitude faster then the original [`faker`](https://github.com/stympy/faker). Maybe use it in the book as well?

Not a real issue though, just a suggestion.

**Comment by ruralocity** [comment]
I'm probably not going to swap them out at this point, but I will add a mention of ffaker as an alternative.

**Comment by ruralocity** [comment]
I've referenced ffaker as an alternative to faker in chapter 4, for the 2013-08-27 release of the book (generating now). Thanks again.
