### ISSUE TITLE
Ch.5, p.49 - Difference between view and template?

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#33]
Is there a difference between a template and a view? If not then only one of them should be used for consistency, if yes, then maybe add a note about it in the book to avoid confusion. It seems like the two are used interchangeably, e.g on page 49 in `contacts_controller_spec.rb` the following test says 'renders the :index **view**':

``` ruby
context 'with params[:letter]' do
  it "populates an array of contacts starting with the letter"
  it "renders the :index view"
end
```

but a couple of lines later it says 'renders the :show **template**':

``` ruby
describe 'GET #show' do
  it "assigns the requested contact to @contact"
  it "renders the :show template"
end
```

**Comment by ruralocity** [comment]
Most Rails developers I know will use them interchangeably, but I standardized on template for the next push.
