### ISSUE TITLE
Mention of factory before actual factory usage

### ISSUE THREAD

**Issue by gmile** [everydayrails/rspec_rails_4#4]
In the pdf version of the book, on page 33, there's a paragraph starting with:

```
Edit the parameters passed to the factory within the expectation.
```

But we're not actually using factories yet, are we?

**Comment by dmke** [comment]
`Contact#create` is an actual factory, but not a FactoryGirl factory ;-)

I suppose the wording is just a little misleading.

**Comment by ruralocity** [comment]
Good catch. That's from an earlier version of the book in which I jumped right in with Factory Girl. I'll change the wording and release a minor update soon.

**Comment by ruralocity** [comment]
I've clarified this language in chapter 3, for the 2013-08-27 release of the book (generating now). Thanks again.
