### ISSUE TITLE
General inconsitency - Use of ' vs " for strings

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#47]
It seems the book has no consistency in its use of ' vs " for strings. Sometimes ' is used in describe blocks, sometimes " is used, sometimes ' is used in context blocks and sometimes not. I feel it would be more professional and less confusing to chose a convention and stick to it.

_Book version: 2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
I'm closing this and flagging it to review the next time I redo the code, which typically happens upon major releases of Rails, RSpec, or Capybara.
