### ISSUE TITLE
Ch.6, p.71 - Chapter reference

### ISSUE THREAD

**Issue by olerass** [everydayrails/rspec_rails_4#51]
Page 71, line 1:

> We've covered an awful lot in this chapter..

This chapter is only 7 pages long. Perhaps what's meant is that we've covered an awful lot in the last **two** chapters?

_Book version: 2013-10-29 (PDF)_

**Comment by ruralocity** [comment]
The controller chapters used to be structured differently. I reworded for the next minor book update.
