### ISSUE TITLE
Ch.4, p.44 - Typo

### ISSUE THREAD

**Issue by pmuens** [everydayrails/rspec_rails_4#52]
# Hot to abuse factories

I think, that this one is a typo.

![bildschirmfoto 2013-11-24 um 19 12 00](https://f.cloud.github.com/assets/1606004/1609184/f4e146ac-5533-11e3-9ab4-84c9ddb9afe9.png)

Great book BTW!
Really a joy to read. Thank you for this one!

**Comment by ruralocity** [comment]
Thanks, @pmuens! I thought I'd fixed this one but will check again and make sure it's addressed in the next release.

Aaron

**Comment by ruralocity** [comment]
Fixed; pending next release.
