### ISSUE TITLE
Ch.3, p.20 - errors_on

### ISSUE THREAD

**Issue by ronangimenes** [everydayrails/rspec_rails_4#54]
I'd like to understand why I changed the expectation errors_on field and the test didn't broke if I use any existing field.

I.e. it pass when I run

  it "is invalid without a firstname" do
    expect(Contact.new(**firstname**: nil)).to have(1).errors_on(**:email**)
  end

**Comment by ruralocity** [comment]
If you're working from the code in the book, then the :email attribute still has a validation on it, and would still fail when you pass in a new Contact with no email attribute assigned.

**Comment by ronangimenes** [comment]
OK, thanks!
