### ISSUE TITLE
Ch.3 p.32 - Wrong edge cases

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#59]
In Ch.3 - Summary

> Test for edge cases: If you have a validation that requires a password be between four and ten characters in length, don't just test an eight-character password and call it good. A good set of tests would test at four and eight, as well as at three and eleven. (Of course, you might also take the opportunity to ask yourself why you'd allow such short passwords, or not allow longer ones. Testing is also a good opportunity to reflect on an application's requirements and code.)

I think "A good set of tests would test at four and eight" should be "A good set of tests would test at four and ten" in this context.

**Comment by ruralocity** [comment]
Fixed for next minor release.
