### ISSUE TITLE
Ch.4, p.39 - Unnecessary block for phone attribute

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#60]
``` ruby
FactoryGirl.define do
  factory :phone do
    association :contact
    phone { '123-555-1234' }
    phone_type 'home'
  end
end
```

In this case, the phone attribute does not require a block, I think.

Some other phone attributes also have such a block.

**Comment by ruralocity** [comment]
You're correct. I will address this in the next major update when I rebuild the application.

**Comment by ruralocity** [comment]
Fixed for the RSpec 3 edition.
