### ISSUE TITLE
git checkout typos

### ISSUE THREAD

**Issue by davidhan527** [everydayrails/rspec_rails_4#66]
Ch. 8 pg. 83

This may be very minor but if you see the screenshot provided, anytime the code is copy & pasted and there is a line break in the git checkout code it includes an unnecessary space that makes the git checkout fail. In this case there is a space before "features" - git checkout -b 08_features origin/08_- features. This is not a big deal for those familiar with git but for very new beginners who aren't familiar it would be confusing. There are other examples like these throughout the book where there is a line break between the git checkout code. 

![everydayrailsrspec_pdf__page_92_of_152_-4](https://f.cloud.github.com/assets/4370987/2041584/e13b89a6-89c6-11e3-8fe6-3a3480025244.jpg)

**Comment by ruralocity** [comment]
Thanks @davidhan527, that's a good observation. I'm away from my computer for the next few days but will correct this when I get back.

**Comment by ruralocity** [comment]
I've fixed this for a minor update I'll push out tonight. Thanks again.
