### ISSUE TITLE
p135 - Text and link do not match version

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#69]
As for Agile Web Development with Rails, in the text it says "the current, fourth edition", but the link points the [Rails4 version](http://pragprog.com/book/rails4/agile-web-development-with-rails), not [the fourth edition](http://pragprog.com/book/rails32/agile-web-development-with-rails-3-2). It might be a little confusing.

**Comment by ruralocity** [comment]
Fixed for the next minor update.
