### ISSUE TITLE
Ch.12 p131 - What is the "old habits?"

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#71]
In the chapter 12, there is a section called "Don't revert to old habits!", but I could not understand what the old habits are, even after I read the section. I expected it would have content like "Do not give up automated testing and revert to browser-click testing even if you get stuck."

**Comment by ruralocity** [comment]
The rest of that paragraph got lost at some point. I've rewritten for a book update, coming tonight.
