### ISSUE TITLE
Ch.3 P.21, etc: Use have(1).error_on instead of have(1).errors_on

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#74]
If code is like `expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)`, using `have(1).error_on` is more natural as English. But newbies might confuse which to use `errors_on` or `error_on` without any clarifications. However, some of RSpec methods have singular and plural form, so it is valuable to mention it.

**Comment by ruralocity** [comment]
I'll address this in the next code update.

**Comment by ruralocity** [comment]
Since `have` has been extracted from the core, and `errors_on` has been removed from rspec-rails, I have rewritten these examples for the RSpec 3 version.
