### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#80]
Some code or terminal output have wrong syntax highlighting. Especially the chapter 11 has many problems.

**Comment by ruralocity** [comment]
I've addressed what I can for the next release. In the case of terminal output I removed highlighting altogether.

**Comment by JunichiIto** [comment]
Without lang option, unknown syntax highlighting is enabled, so I recommend to specify lang=text.
I captured an example from Ch.11 p109, the latest version:

![screen shot 2014-02-24 at 9 12 36](https://f.cloud.github.com/assets/1148320/2241865/6a6ca79e-9ce8-11e3-95f6-3c396f6f911f.png)
