### ISSUE TITLE
Ch 9 p104 - Streamline CSS compilation?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#83]
In Ch 9 p104, you wrote (Guard) can streamline CSS compilation, but what do you mean CSS compilation? I guess they are [guard-less](https://github.com/guard/guard-compass), [guard-compass](https://github.com/guard/guard-compass) and so on. If so, I recommend to write so. It might be hard for newbies to imagine what CSS compilation is.

**Comment by ruralocity** [comment]
I expect readers to have some exposure to Rails before picking up this book, so they should hopefully at least have heard of the asset pipeline and Sass. I have clarified the sentence, though, to express what I mean.
