### ISSUE TITLE
Don't you mention that "before do" is the same as "before :each do"?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#85]
In this book, all before blocks have `:each` argument, but [:each is the default, so before do is the same as before(:each)](http://old.rspec.info/documentation/before_and_after.html). Actually I always write `before do`. I think it is worth mentioning.

**Comment by ruralocity** [comment]
I've added an aside for it. I prefer the explicitness of `:each` but others can make their own decision.
