### ISSUE TITLE
Ch.3 p26 - eq and include come from rspec-expectations?

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#88]
In Ch.3 p26, the book says "`eq` and `include` come from `rspec-matchers`" but they come from `rspec-expectations` gem, correct?

http://rubydoc.info/gems/rspec-expectations/RSpec/Matchers#eq-instance_method
http://rubydoc.info/gems/rspec-expectations/RSpec/Matchers#include-instance_method

**Comment by ruralocity** [comment]
You're right. I fixed that in one place but not the other. Fixed for the next release.
