### ISSUE TITLE
Ch.4 p40 - Options for "expect(create(:contact).phones.count).to eq 3"

### ISSUE THREAD

**Issue by JunichiIto** [everydayrails/rspec_rails_4#94]
`expect(create(:contact).phones.count).to eq 3` is easy to understand for newbies, but there are more options for it:

``` ruby
expect(create(:contact).phones).to have(3).items
# or
expect(create(:contact)).to have(3).phones
```

I feel they are terser and more readable, so maybe worth mentioning.

**Comment by JunichiIto** [comment]
In RSpec 3, `have(x).items` will be moved into an external gem, so maybe my idea is not so good:

http://myronmars.to/n/dev-blog/2013/07/the-plan-for-rspec-3

**Comment by ruralocity** [comment]
Yes, let's leave it as-is.
