### ISSUE TITLE
Ch.2 p47: Suggest Rails Composer instead of Rails Wizard

### ISSUE THREAD

**Issue by DanielKehoe** [everydayrails/rspec_rails_4#97]
In the last paragraph of Chapter 2, you mention Rails Wizard and App Scrolls. Rails Wizard hasn't been maintained in over three years, App Scrolls hasn't been touched in a year. You might mention Rails Composer [1], an application template based on the rails_apps_composer gem, which is my fork of Rails Wizard [2], and actively maintained. The README has a section "About Rails Application Templates" which provides links to various guides that show how to create application templates.

[1] https://github.com/RailsApps/rails-composer
[2] https://github.com/RailsApps/rails_apps_composer

Your book is awesome, BTW :-)

**Comment by ruralocity** [comment]
Thanks Daniel! I'll make the switch when I write the Rails 4.1/RSpec 3 updates.

**Comment by ruralocity** [comment]
Hey Daniel, I've made the switch in the forthcoming RSpec 3/Rails 4.1 update. I'm still a few weeks out from releasing it, but I'm going to go ahead and close this in the meantime to knock it off my to-do list :)

Thanks again,
Aaron

**Comment by DanielKehoe** [comment]
I'm looking forward to the new edition.
