### ISSUE TITLE
Ch.3 Failure/Error: expect(Contact.new(firstname: nil))

### ISSUE THREAD

**Issue by malopezcruz** [everydayrails/rspec_rails_4#98]
In chapter 3, second test... Anyone know why I get this error and how can I solve it? The test should pass.

```
1) Contact is invalid without firstname
     Failure/Error: expect(Contact.new(firstname: nil)).to have(1).errors_on(:firstname)
       expected 1 errors on :firstname, got 0
     # ./spec/models/contact_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by ruralocity** [comment]
Sorry I missed this issue before ... hopefully you've figured it out by now. If not, can you share your contact.rb file's contents?

As a related aside, RSpec 3 changes how this style of test works, so I'll be providing different examples when the updated book is ready. They will look something like this:

```
it "is invalid without a firstname" do
  contact = Contact.new(firstname: nil)
  contact.valid?
  expect(contact.errors[:firstname]).to include("can't be blank")
end
```

**Comment by ruralocity** [comment]
Closing this issue; feel free to reopen if you still have questions about the spec.

Aaron
